# Generated by Django 5.1.3 on 2024-11-14 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_list',
            old_name='custome_ph_number',
            new_name='customer_ph_number',
        ),
    ]
