# Generated by Django 5.1.3 on 2024-11-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_custome_ph_number_customer_list_customer_ph_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_list',
            old_name='customer_id',
            new_name='customer_number',
        ),
    ]
