# Generated by Django 5.1.3 on 2024-11-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_list_customer_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='category_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
