# Generated by Django 5.1.3 on 2024-11-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_list_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
