# Generated by Django 5.1.3 on 2024-11-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_list_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_list',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
