# Generated by Django 5.1.3 on 2024-11-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer_list_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_list',
            name='joined_date',
            field=models.DateField(),
        ),
    ]
