# Generated by Django 5.1.3 on 2024-11-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customer_list_joined_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_list',
            old_name='joined_date',
            new_name='purchased_date',
        ),
        migrations.AddField(
            model_name='customer_list',
            name='total_spend',
            field=models.DecimalField(decimal_places=2, default=2.2, max_digits=10),
            preserve_default=False,
        ),
    ]
